version: "3.8"
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      - C:/pgadmin4-data:/var/lib/pgadmin

  openpim:
    image: openpim/production:1.3
    depends_on:
      postgres:
        condition: service_started
    ports:
      - 8081:80
  
  pgadmin:
    image: dpage/pgadmin4:6.5
    restart: always
    ports:
      - 8082:80