version: "3.8"
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Its@m3time!
    volumes:
      - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgadmin4-data:/var/lib/pgadmin

  openpim:
    image: openpim/production:1.3
    environment:
      OPENPIM_DATABASE_ADDRESS: postgres
      OPENPIM_DATABASE_PASSWORD: Its@m3time!
    depends_on:
      postgres:
        condition: service_started
    ports:
      - 80:80
    hostname: openpim.alltheragesutilities.net
  
  pgadmin:
    image: dpage/pgadmin4:6.5
    restart: always
    ports:
      - 8080:80
    hostname: pimadmin.alltheragesutilities.net